/**
 * Nawasrah Business Manager - Initial Seed Mock Data
 */

import { Customer, Expense, Invoice, Order, Product, Shift, Supplier, User } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'u-owner-1',
    name: 'أحمد النواصرة',
    email: 'owner@nawasrah.jo',
    phone: '0791234567',
    role: 'Owner',
    branchId: 'b-amman-main',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    jobTitle: 'المدير العام والمالك',
    language: 'ar',
    timezone: 'Asia/Amman',
    address: 'عمّان - شارع الملك عبدالله الثاني، مجمع النواصرة',
    whatsapp: '0791234567',
    themeMode: 'dark',
    permissions: [], // Owner bypasses
    isActive: true,
    lastLogin: new Date().toISOString(),
    notificationSettings: {
      newOrders: true,
      stockAlerts: true,
      expiryAlerts: true,
      debtAlerts: true,
      emailAlerts: true,
      pushAlerts: true,
      smsAlerts: false,
      soundAlerts: true,
    },
    activeSessions: [
      {
        id: 'sess-current',
        device: 'iPhone 15 Pro Max (iOS 17.5) - Amman',
        ip: '185.220.101.4',
        lastActive: 'الآن (الجلسة الحالية)',
        isCurrent: true,
      },
      {
        id: 'sess-macbook',
        device: 'MacBook Pro 16" M3 (Chrome 126)',
        ip: '185.220.101.12',
        lastActive: 'قبل ساعتين',
        isCurrent: false,
      },
      {
        id: 'sess-pos',
        device: 'POS Terminal #01 - الفرع الرئيسي',
        ip: '192.168.1.105',
        lastActive: 'أمس الساعة 05:30 م',
        isCurrent: false,
      },
    ],
  },
  {
    id: 'u-admin-1',
    name: 'سارة العبادي',
    email: 'admin@nawasrah.jo',
    phone: '0788887766',
    role: 'Admin',
    branchId: 'b-amman-main',
    jobTitle: 'مديرة العمليات والمخزون',
    language: 'ar',
    timezone: 'Asia/Amman',
    permissions: [],
    isActive: true,
  },
  {
    id: 'u-cashier-1',
    name: 'محمد حسن',
    email: 'cashier@nawasrah.jo',
    phone: '0775554433',
    role: 'Cashier',
    branchId: 'b-amman-main',
    jobTitle: 'محاسب كاشير الرئيسي',
    language: 'ar',
    timezone: 'Asia/Amman',
    permissions: [],
    isActive: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-101',
    sku: 'NWS-WTR-330',
    barcode: '6251234567890',
    nameAr: 'مياه مزمز فاخرة 330مل (عبوة)',
    nameEn: 'Mazmaz Premium Water 330ml Box',
    description: 'كرتونة مياه شرب نقية تحتوي على 40 عبوة عالية الجودة.',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&q=80&w=400',
    categoryId: 'cat-1',
    purchasePackage: 'كرتونة',
    unitsPerPackage: 40,
    defaultPurchasePrice: 72.00,
    costPrice: 1.80,
    retailPrice: 2.80,
    wholesalePrice: 2.30,
    profitPerPiece: 1.00,
    profitPercentage: 55.56,
    promoPrice: 2.50,
    taxRate: 16,
    unit: 'قطعة',
    packetSize: 1,
    cartonSize: 40,
    onHandQuantity: 120,
    reservedQuantity: 10,
    availableQuantity: 110,
    reorderLevel: 25,
    expiryDate: '2026-12-31',
    batchNumber: 'BATCH-2026-A1',
    countryOfOrigin: 'الأردن',
    warehouseLocation: 'رف A-12',
    status: 'active',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-07-20T14:30:00Z',
  },
  {
    id: 'prod-102',
    sku: 'NWS-CHK-NUT',
    barcode: '6259876543210',
    nameAr: 'شوكولاتة دكّان %70 بالمكسرات',
    nameEn: 'Dokkan 70% Dark Chocolate with Nuts',
    description: 'شوكولاتة داكنة فاخرة محشوة بالفستق الحلبي والبندق.',
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&q=80&w=400',
    categoryId: 'cat-2',
    purchasePackage: 'كرتونة',
    unitsPerPackage: 24,
    defaultPurchasePrice: 28.80,
    costPrice: 1.20,
    retailPrice: 2.20,
    wholesalePrice: 1.80,
    profitPerPiece: 1.00,
    profitPercentage: 83.33,
    taxRate: 16,
    unit: 'قطعة',
    packetSize: 12,
    cartonSize: 144,
    onHandQuantity: 45,
    reservedQuantity: 5,
    availableQuantity: 40,
    reorderLevel: 15,
    expiryDate: '2026-11-15',
    batchNumber: 'CHK-9921',
    countryOfOrigin: 'تركيا',
    warehouseLocation: 'رف B-04',
    status: 'near_expiry',
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-07-21T08:15:00Z',
  },
  {
    id: 'prod-103',
    sku: 'NWS-NUT-PST',
    barcode: '6251122334455',
    nameAr: 'فستق حلبي محمص فاخر 500غ',
    nameEn: 'Roasted Premium Pistachio 500g',
    description: 'فستق حلبي جامبو محمص ومملح خفيفاً.',
    imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=400',
    categoryId: 'cat-3',
    purchasePackage: 'صندوق',
    unitsPerPackage: 20,
    defaultPurchasePrice: 90.00,
    costPrice: 4.50,
    retailPrice: 7.50,
    wholesalePrice: 6.20,
    profitPerPiece: 3.00,
    profitPercentage: 66.67,
    taxRate: 16,
    unit: 'باكيت',
    packetSize: 1,
    cartonSize: 20,
    onHandQuantity: 8,
    reservedQuantity: 0,
    availableQuantity: 8,
    reorderLevel: 10,
    expiryDate: '2027-03-30',
    batchNumber: 'PST-0032',
    countryOfOrigin: 'سوريا',
    warehouseLocation: 'رف C-01',
    status: 'near_expiry', // low stock warning
    createdAt: '2026-03-12T11:20:00Z',
    updatedAt: '2026-07-22T10:00:00Z',
  },
  {
    id: 'prod-104',
    sku: 'NWS-ENG-TURBO',
    barcode: '6253344556677',
    nameAr: 'طقم توربو رياضي معدل - فئة A',
    nameEn: 'Performance Turbo Kit - Grade A',
    description: 'قطع غيار توربو عالي الكفاءة للمحركات الرياضية.',
    imageUrl: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&q=80&w=400',
    categoryId: 'cat-5',
    costPrice: 180.00,
    retailPrice: 245.00,
    wholesalePrice: 210.00,
    taxRate: 16,
    unit: 'قطعة',
    packetSize: 1,
    cartonSize: 4,
    onHandQuantity: 12,
    reservedQuantity: 2,
    availableQuantity: 10,
    reorderLevel: 3,
    expiryDate: '2030-01-01',
    batchNumber: 'TURBO-2026-X',
    countryOfOrigin: 'ألمانيا',
    warehouseLocation: 'مستودع القطع - W1',
    status: 'active',
    createdAt: '2026-04-05T14:10:00Z',
    updatedAt: '2026-07-22T12:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1025',
    orderNumber: 'ORD-#1025',
    customerName: 'عبدالرحمن الباسم',
    customerPhone: '0798765432',
    governorate: 'عمان',
    region: 'خلدا',
    address: 'شارع الملك عبدالله الثاني، بناية رقم 45 - الشقة 302',
    customerAddress: {
      governorate: 'عمان',
      area: 'خلدا',
      street: 'شارع الملك عبدالله الثاني',
      building: 'بناية أوركيد رقم 45',
      apartment: 'طابق 3 - شقة 302',
      landmark: 'بجانب أسواق الفريد وقرب صيدلية فارمسي وان',
      deliveryNotes: 'الرجاء الاتصال قبل الوصول بـ 10 دقائق المصعد يعمل والتوصيل للباب',
    },
    latitude: 31.9833,
    longitude: 35.8500,
    formattedAddress: 'شارع الملك عبدالله الثاني، بناية 45، ط3 ش302، خلدا، عمان',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=31.9833,35.8500',
    mapUrl: 'https://maps.google.com/?q=31.9833,35.8500',
    locationSource: 'gps',
    locationConfirmed: true,
    items: [
      {
        id: 'item-1',
        productId: 'prod-101',
        productName: 'مياه مزمز فاخرة 330مل (كرتونة)',
        productImage: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&q=80&w=400',
        sku: 'NWS-WTR-330',
        unit: 'كرتونة',
        unitPrice: 2.80,
        costPrice: 1.80,
        quantity: 5,
        discount: 0,
        totalPrice: 14.00,
      },
      {
        id: 'item-2',
        productId: 'prod-102',
        productName: 'شوكولاتة دكّان %70 بالمكسرات',
        productImage: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&q=80&w=400',
        sku: 'NWS-CHK-NUT',
        unit: 'قطعة',
        unitPrice: 2.20,
        costPrice: 1.20,
        quantity: 4,
        discount: 0.80,
        totalPrice: 8.00,
      },
    ],
    subtotal: 22.00,
    discount: 0.80,
    deliveryFee: 2.50,
    totalAmount: 23.70,
    paymentMethod: 'cliq',
    paymentStatus: 'paid',
    status: 'new',
    branchId: 'b-amman-main',
    isNew: true,
    notes: 'يرجى التوصيل بعد الساعة 4 مساءً',
    internalNotes: 'الطلب قادم من متجر الزبائن الإلكتروني عبر الموقع',
    createdAt: '2026-07-22T20:15:00Z',
    updatedAt: '2026-07-22T20:15:00Z',
    statusHistory: [
      { status: 'new', changedAt: '2026-07-22T20:15:00Z', changedBy: 'نظام متجر الزبائن' },
    ],
  },
  {
    id: 'ord-1024',
    orderNumber: 'ORD-#1024',
    customerName: 'مؤسسة القدس للمقاولات',
    customerPhone: '0771223344',
    governorate: 'عمان',
    region: 'الشميساني',
    address: 'شارع جابر بن حيان، مجمع القدس التجاري',
    customerAddress: {
      governorate: 'عمان',
      area: 'الشميساني',
      street: 'شارع جابر بن حيان',
      building: 'مجمع القدس التجاري - رقم 12',
      apartment: 'مكتب رقم 401',
      landmark: 'مقابل البنك العربي الرئيسي',
      deliveryNotes: 'التسليم للمكتب في الساعات المكتبية من 9 إلى 5',
    },
    latitude: 31.9600,
    longitude: 35.9000,
    formattedAddress: 'شارع جابر بن حيان، مجمع القدس التجاري، الشميساني، عمان',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=31.9600,35.9000',
    mapUrl: 'https://maps.google.com/?q=31.9600,35.9000',
    locationSource: 'map_pin',
    locationConfirmed: true,
    items: [
      {
        id: 'item-3',
        productId: 'prod-104',
        productName: 'طقم توربو رياضي معدل - فئة A',
        productImage: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&q=80&w=400',
        sku: 'NWS-ENG-TURBO',
        unit: 'قطعة',
        unitPrice: 245.00,
        costPrice: 180.00,
        quantity: 2,
        discount: 10.00,
        totalPrice: 480.00,
      },
    ],
    subtotal: 490.00,
    discount: 10.00,
    deliveryFee: 0,
    totalAmount: 480.00,
    paymentMethod: 'debt',
    paymentStatus: 'unpaid',
    status: 'processing',
    branchId: 'b-amman-main',
    isNew: false,
    notes: 'فاتورة آجل تحسب على حساب المؤسسة',
    createdAt: '2026-07-22T18:00:00Z',
    updatedAt: '2026-07-22T18:30:00Z',
    statusHistory: [
      { status: 'new', changedAt: '2026-07-22T18:00:00Z', changedBy: 'أحمد النواصرة' },
      { status: 'confirmed', changedAt: '2026-07-22T18:10:00Z', changedBy: 'أحمد النواصرة' },
      { status: 'processing', changedAt: '2026-07-22T18:30:00Z', changedBy: 'محمد حسن' },
    ],
  },
  {
    id: 'ord-1023',
    orderNumber: 'ORD-#1023',
    customerName: 'سامر التميمي',
    customerPhone: '0785544332',
    governorate: 'إربد',
    region: 'حي الجامعات',
    address: 'إربد - قرب دوار القبة، خلف سوبرماركت السعادة',
    customerAddress: {
      governorate: 'إربد',
      area: 'حي الجامعات',
      street: 'شارع الجامعة الرئيسي',
      building: 'بناية التميمي',
      landmark: 'خلف سوبرماركت السعادة، قرب دوار القبة',
      deliveryNotes: 'عنوان مكتوب يدوياً - يتطلب تأكيد اللوكيشن قبل تحريك السائق',
    },
    latitude: undefined,
    longitude: undefined,
    formattedAddress: 'إربد - حي الجامعات - قرب دوار القبة',
    locationSource: 'manual',
    locationConfirmed: false,
    items: [
      {
        id: 'item-4',
        productId: 'prod-103',
        productName: 'فستق حلبي محمص فاخر 500غ',
        productImage: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=400',
        sku: 'NWS-NUT-PST',
        unit: 'باكيت',
        unitPrice: 7.50,
        costPrice: 4.50,
        quantity: 3,
        discount: 0,
        totalPrice: 22.50,
      },
    ],
    subtotal: 22.50,
    discount: 0,
    deliveryFee: 2.00,
    totalAmount: 24.50,
    paymentMethod: 'cash',
    paymentStatus: 'unpaid',
    status: 'new',
    branchId: 'b-irbid',
    isNew: true,
    notes: 'عنوان يدوي يرجى التأكد من لوكيشن الواتساب',
    createdAt: '2026-07-22T16:00:00Z',
    updatedAt: '2026-07-22T16:00:00Z',
    statusHistory: [
      { status: 'new', changedAt: '2026-07-22T16:00:00Z', changedBy: 'نظام الطلبات' },
    ],
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'شركة الأمل التجاريّة',
    phone: '065500111',
    whatsapp: '962795500111',
    address: 'شارع مكة، عمّان',
    governorate: 'عمان',
    customerType: 'wholesale',
    creditLimit: 5000,
    paymentTermDays: 30,
    currentBalance: 2450.00,
    totalOrdersCount: 18,
    notes: 'عميل ممتاز يلتزم بالسداد في الوقت المحدد',
    createdAt: '2025-11-01T00:00:00Z',
  },
  {
    id: 'cust-2',
    name: 'مؤسسة القدس للمقاولات',
    phone: '0771223344',
    whatsapp: '962771223344',
    address: 'الشميساني، مجمع القدس',
    governorate: 'عمان',
    customerType: 'wholesale',
    creditLimit: 10000,
    paymentTermDays: 45,
    currentBalance: 8900.25,
    totalOrdersCount: 32,
    createdAt: '2025-08-15T00:00:00Z',
  },
  {
    id: 'cust-3',
    name: 'ليلى سعيد العبادي',
    phone: '0796655443',
    whatsapp: '962796655443',
    address: 'الصويفية، الدوار السادس',
    governorate: 'عمان',
    customerType: 'retail',
    creditLimit: 500,
    paymentTermDays: 14,
    currentBalance: 0,
    totalOrdersCount: 5,
    createdAt: '2026-02-10T00:00:00Z',
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    companyName: 'شركة الموارد الدولية للتوزيع',
    contactPerson: 'حسن الخطيب',
    phone: '065112233',
    whatsapp: '962795112233',
    address: 'المنطقة الصناعية - سحاب',
    currentBalance: 12500.00,
    taxNumber: '123456789',
    notes: 'مورد مياه ومشروبات رئيسي',
  },
  {
    id: 'sup-2',
    companyName: 'مصنع الأردن للحلويات والشوكولاتة',
    contactPerson: 'عمر القاسم',
    phone: '053887766',
    whatsapp: '962783887766',
    address: 'المنطقة الحرة - الزرقاء',
    currentBalance: 5950.00,
    taxNumber: '987654321',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    expenseNumber: 'EXP-2026-081',
    category: 'إيجار',
    amount: 550.00,
    paymentMethod: 'bank_transfer',
    description: 'دفع إيجار الفرع الرئيسي لشهر تموز',
    isApproved: true,
    approvedBy: 'أحمد النواصرة',
    branchId: 'b-amman-main',
    createdByName: 'سارة العبادي',
    createdAt: '2026-07-01T09:00:00Z',
  },
  {
    id: 'exp-2',
    expenseNumber: 'EXP-2026-092',
    category: 'كهرباء',
    amount: 124.50,
    paymentMethod: 'cliq',
    description: 'فاتورة كهرباء فرع عمان لشهر حزيران',
    isApproved: true,
    approvedBy: 'أحمد النواصرة',
    branchId: 'b-amman-main',
    createdByName: 'محمد حسن',
    createdAt: '2026-07-15T11:30:00Z',
  },
];

export const INITIAL_SHIFT: Shift = {
  id: 'shf-889',
  shiftNumber: 'SHF-2026-07-22-A',
  branchId: 'b-amman-main',
  cashierName: 'محمد حسن',
  startTime: '2026-07-22T08:00:00Z',
  openingCash: 250.00,
  totalCashSales: 1240.00,
  totalCliqSales: 680.00,
  totalCardSales: 450.00,
  totalReceipts: 300.00,
  totalPayments: 124.50,
  expectedCash: 1665.50, // 250 + 1240 + 300 - 124.50
  status: 'open',
};

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-8821',
    invoiceNumber: 'INV-2026-08821',
    customerName: 'شركة الأمل التجاريّة',
    items: [
      {
        id: 'ii-1',
        productId: 'prod-101',
        productName: 'مياه مزمز فاخرة 330مل (كرتونة)',
        productImage: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&q=80&w=400',
        sku: 'NWS-WTR-330',
        unit: 'كرتونة',
        unitPrice: 2.80,
        costPrice: 1.80,
        quantity: 20,
        discount: 0,
        totalPrice: 56.00,
      },
    ],
    subtotal: 56.00,
    discount: 0,
    taxAmount: 8.96,
    totalAmount: 64.96,
    paidAmount: 64.96,
    remainingAmount: 0,
    paymentMethod: 'cliq',
    status: 'posted',
    branchId: 'b-amman-main',
    createdById: 'u-cashier-1',
    createdByName: 'محمد حسن',
    createdAt: '2026-07-22T14:10:00Z',
  },
];
